spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
    metadataMap:
    zone: zone2
  client:
    serviceUrl:
    defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/
    registerWithEureka: true
    fetchRegistry: true
server:
  port: ${PORT:8762}
