spring:
  application:
    name: register-service
server:
  port:${PORT:8081}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    instanceId: ${spring.application.name}-${SEQUENCE_NO} # config instanceid 
