
# user name and password ftp server
ftp.url=192.168.192.128:22022
ftp.username=ftp_test
ftp.password=ftp_test_pw

  # Local working directory
ftp.local.work.directory=D:/TestData/sunknew/sftp/temp
  # Local synchronization directory
ftp.local.data.dir=D:/TestData/sunknew/sftp/data

ftp.server.uri=sftp://${ftp.url}\
  ?username=${ftp.username}\
  &password=${ftp.password}\
  &useUserKnownHostsFile=false\
  &localWorkDirectory=${ftp.local.work.directory}\
  &delay=1h\
  &readLock=rename\
  &filter=#ftpDownloadFileFilter\
  &stepwise=false
